/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer */

#ifndef _Included_com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer
#define _Included_com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer
 * Method:    open
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer_close
  (JNIEnv *, jobject);

/*
 * Class:     com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer
 * Method:    setProperty
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer_setProperty
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
