/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer_Companion */

#ifndef _Included_com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer_Companion
#define _Included_com_guillaumepayet_remotenumpadserver_connection_bluetooth_NativeServer_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
